---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    debug.openshift.io/source-container: container-00
    openshift.io/scc: node-exporter
  namespace: {{ DEFAULT_NAMESPACE }}
  name: debug
spec:
  selector:
    matchLabels:
      test-network-function.com/app: debug
  template:
    metadata:
      labels:
        test-network-function.com/skip_connectivity_test: ""
        test-network-function.com/app: debug
      name: debug
    spec:
      #{{NODE_SELECTOR}}
      containers:
        - command:
            - /bin/sh
          image: "{{TNF_PARTNER_REPO}}/{{SUPPORT_IMAGE}}"
          imagePullPolicy: Always
          name: container-00
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
          stdin: true
          stdinOnce: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /host
              name: host
      enableServiceLinks: true
      hostNetwork: true
      hostPID: true
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - hostPath:
            path: /
            type: Directory
          name: host
