FROM registry.access.redhat.com/ubi8/ubi:latest

RUN \
    yum -y update && \
    yum -y install pciutils util-linux net-tools procps-ng iputils iproute jq libselinux-utils iptables nftables ethtool && \
    yum clean all -y && \
    rm -rf /var/cache/yum

VOLUME ["/host"]
