# IMPORTANT: podman must be build from ubi8.x only. Do not upgrade it to ubi9.
FROM registry.access.redhat.com/ubi8/ubi:8.10-1132.1733300785 as podman-builder

# hadolint ignore=DL3041
RUN \
	dnf update --assumeyes --disableplugin=subscription-manager \
	&& dnf install --assumeyes --disableplugin=subscription-manager \
		git \
		make \
		golang \
		gpgme-devel \
		libseccomp-devel \
		libassuan-devel \
		python3 \
	&& dnf clean all \
	&& git clone https://github.com/containers/podman.git
WORKDIR /podman
RUN \
	git checkout v4.9.5 \
	&& make

FROM registry.access.redhat.com/ubi9/ubi:9.5
# hadolint ignore=DL3041
RUN \
	dnf update --assumeyes --disableplugin=subscription-manager \
	&& dnf install --assumeyes --disableplugin=subscription-manager \
		ethtool \
		iproute \
		iptables \
		iputils \
		jq \
		libselinux-utils \
		net-tools \
		nftables \
		pciutils \
		procps-ng \
		util-linux \
	&& dnf clean all --assumeyes --disableplugin=subscription-manager \
	&& rm -fr /var/cache/yum \
	&& mkdir /root/podman
COPY --from=podman-builder /podman/bin/podman /root/podman/
VOLUME ["/host"]
