---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: test
spec:
  containers:
    - command:
        - tail
        - -f
        - /dev/null
      image: quay.io/testnetworkfunction/cnf-test-partner:latest
      name: test
      resources:
        limits:
          memory: 512Mi
          cpu: 0.25
  restartPolicy: Always
