apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-subscription
  namespace: {{ TNF_EXAMPLE_CNF_NAMESPACE }} 
spec:
  channel: alpha
  name: {{ OPERATOR_BASE }}
  source: {{ CATALOG_SOURCE }}
  sourceNamespace: {{ CATALOG_NAMESPACE }}
  installPlanApproval: Manual
  startingCSV: {{ OPERATOR_NAME }}
