---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-exclusive-sched-rt-app
  namespace: {{ TNF_EXAMPLE_CNF_NAMESPACE }}
  labels:
    test-network-function.com/container: target
    test-network-function.com/generic: target
    test-network-function.com/feature: performance
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: busybox
      image: busybox:1.28
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        limits:
          cpu: "1"
          memory: "100Mi"
        requests:
          cpu: "1"
