---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-shared-sched-non-rt-app
  namespace: {{ CERTSUITE_EXAMPLE_NAMESPACE }}
  labels:
    test-network-function.com/container: target
    test-network-function.com/generic: target
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: busybox
      image: busybox:1.28
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "250m"
