---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-exclusive-sched-rt-app
  namespace: {{ CERTSUITE_EXAMPLE_NAMESPACE }}
  labels:
    redhat-best-practices-for-k8s.com/container: target
    redhat-best-practices-for-k8s.com/generic: target
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: busybox
      image: busybox:1.28
      command: [ "sh", "-c", "sleep 1h" ]
      resources:
        limits:
          cpu: "1"
          memory: "100Mi"
        requests:
          cpu: "1"
