---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector:
    matchLabels:
      redhat-best-practices-for-k8s.com/container: target
  policyTypes:
    - Ingress
