---
apiVersion: apps/v1
kind: {{ RESOURCE_TYPE }}
metadata:
  labels:
    redhat-best-practices-for-k8s.com/generic: target
  name: test
  namespace: {{ CERTSUITE_EXAMPLE_NAMESPACE }}
spec:
  replicas: {{ REPLICAS }}
  selector:
    matchLabels:
      app: {{ APP }}
  template:
    metadata:
      labels:
        app: {{ APP }}
        redhat-best-practices-for-k8s.com/generic: target
        redhat-best-practices-for-k8s.com/container: target
      annotations:
        redhat-best-practices-for-k8s.com/container_tests: '["PRIVILEGED_POD","PRIVILEGED_ROLE"]' # optional
        redhat-best-practices-for-k8s.com/defaultnetworkinterface: '"eth0"' # optional
        k8s.v1.cni.cncf.io/networks: '{{ MULTUS_ANNOTATION }}'
      name: test
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      serviceAccountName: test-pod-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ SC_RUN_AS_USER }}
      containers:
        - image: quay.io/redhat-best-practices-for-k8s/certsuite-sample-workload:latest
          imagePullPolicy: IfNotPresent
          name: test
          ports:
            - name: "http-probe"
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 0.25
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo Hello from the postStart handler"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "killall -0 tail"]
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              httpHeaders:
                - name: health-check
                  value: liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
              httpHeaders:
                - name: health-check
                  value: readiness
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 8080
              httpHeaders:
                - name: health-check
                  value: startup
            failureThreshold: 10
            periodSeconds: 5
          command: ["./bin/app"]
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: test-pvc
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ APP }}
              topologyKey: "kubernetes.io/hostname"
