---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ops

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-apps

--- 
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nginx-og
  namespace: nginx-ops
spec:
  targetNamespaces:
    - nginx-apps

--- 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nginx-ingress-operator
  namespace: nginx-ops
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: nginx-ingress-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace

