---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
spec:
  podSelector:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: tnf
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: tnf
