---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace
spec:
  podSelector:
    matchLabels:
      redhat-best-practices-for-k8s.com/container: target
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ CERTSUITE_EXAMPLE_NAMESPACE }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ CERTSUITE_EXAMPLE_NAMESPACE }}
