apiVersion: v1
kind: Service
metadata:
  name: {{ SERVICE_NAME }}      
  namespace: {{ CERTSUITE_EXAMPLE_NAMESPACE }}
  labels:  
    app: {{ APP }}  
spec:
  ipFamilyPolicy: {{ IP_FAMILY_POLICY }}
  ipFamilies: {{ IP_FAMILIES }}
  selector:
    app: {{ APP }}
  ports:
    - protocol: TCP
      port: 8080
