---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: replicatest
  name: replicatest
  namespace: tnf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: replicatest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: replicatest
        redhat-best-practices-for-k8s.com/generic: target
        redhat-best-practices-for-k8s.com/container: target
    spec:
      terminationGracePeriodSeconds: 50
      containers:
        - image: nginx
          name: replicatest
          resources: {}
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - "echo 'hello world'"
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - "echo 'hello world'"
