---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: imagepullpolicypod
    app: test
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
  name: imagepullpolicypod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 50
  containers:
    - image: nginx
      imagePullPolicy: Always  # This should be IfNotPresent
      name: imagepullpolicypod
      resources: {}
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/bash
              - -c
              - "echo 'hello world'"
        preStop:
          exec:
            command:
              - /bin/bash
              - -c
              - "echo 'hello world'"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
