---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podownertypetest
    app: test
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
  name: podownertypetest
  namespace: tnf
spec:
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 50
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: podownertypetest
      resources: {}
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/bash
              - -c
              - "echo 'hello world'"
        preStop:
          exec:
            command:
              - /bin/bash
              - -c
              - "echo 'hello world'"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
