---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: prestoppod
    app: test
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
  name: prestoppod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 50
  containers:
    - image: nginx
      name: prestoppod
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
