---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: terminationpod
    app: test
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
  name: terminationpod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  # terminationGracePeriodSeconds: 50
  containers:
    - image: nginx
      name: terminationpod
      resources: {}
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/bash
              - -c
              - "echo 'hello world'"
        preStop:
          exec:
            command:
              - /bin/bash
              - -c
              - "echo 'hello world'"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
