# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.synced_folder '../..', '/home/vagrant/partner'
  config.vm.synced_folder 'kubeconfig', '/home/vagrant/.kube'
  config.vm.network 'forwarded_port', guest: 6443, host: 6443

  config.vm.define 'k8shost' do |k8shost|
    k8shost.vm.box = 'generic/fedora36'
    k8shost.vm.hostname = 'k8shost'
    k8shost.vm.network 'private_network', ip: '192.168.56.10'
    k8shost.vm.provider 'virtualbox' do |vb|
      vb.memory = 8096
      vb.cpus = 4
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end

    # Install Go
    k8shost.vm.provision 'shell',
                         path: 'scripts/bootstrap-golang-fedora.sh',
                         privileged: false

    # Configures docker.
    k8shost.vm.provision 'shell',
                         path: 'scripts/bootstrap-docker-fedora.sh',
                         privileged: false

    # Configures python, pip, and j2cli.
    k8shost.vm.provision 'shell',
                         path: 'scripts/bootstrap-python-fedora.sh',
                         privileged: false

    # Triggers reload to setup docker rootless permissions.
    k8shost.vm.provision :reload

    # Download KIND and Kubectl/OC binaries
    k8shost.vm.provision 'shell',
                         path: 'scripts/bootstrap-cluster.sh',
                         privileged: false
    
    # Build the KIND cluster and install the resources
    k8shost.vm.provision 'shell',
                         inline: 'cd partner; make rebuild-cluster; make install',
                         privileged: false
  end
end
