apiVersion: v1
kind: Pod
metadata:
  name: pod2mhugepages
  namespace: tnf
  labels:
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
spec:
  containers:
    - name: example
      image: fedora:latest
      command:
        - sleep
        - inf
      volumeMounts:
        - mountPath: /hugepages-2Mi
          name: hugepage-2mi
      resources:
        limits:
          hugepages-2Mi: 100Mi
          memory: 100Mi
        requests:
          memory: 100Mi
  volumes:
    - name: hugepage-2mi
      emptyDir:
        medium: HugePages-2Mi
