---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loggingpod
    app: test
    test-network-function.com/generic: target
    test-network-function.com/container: target
  name: loggingpod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  containers:
    - image: hashicorp/http-echo
      args:
        - "-text=banana"
      name: loggingpod
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
