---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hostportpod
    app: test
    test-network-function.com/generic: target
    test-network-function.com/container: target
  name: hostportpod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  containers:
    - image: nginx
      name: hostportpod
      resources: {}
      ports:
        - hostPort: 8989
          containerPort: 8989
  dnsPolicy: ClusterFirst
  restartPolicy: Always
