---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ipclockpod
    app: test
    test-network-function.com/generic: target
    test-network-function.com/container: target
  name: ipclockpod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  containers:
    - image: nginx
      name: ipclockpod
      resources: {}
      securityContext:
        capabilities:
          add: ["IPC_LOCK"]  # IPC_LOCK should not be set.
  dnsPolicy: ClusterFirst
  restartPolicy: Always
