---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: netrawpod
    app: test
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
  name: netrawpod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  containers:
    - image: nginx
      name: netrawpod
      resources: {}
      securityContext:
        capabilities:
          add: ["NET_RAW"]  # NET_RAW should not be set.
  dnsPolicy: ClusterFirst
  restartPolicy: Always
