apiVersion: v1
kind: Pod
metadata:
  name: sa-token-test
  namespace: tnf
  labels:
    redhat-best-practices-for-k8s.com/generic: target
spec:
  containers:
    - name: container-test
      image: nginx
      volumeMounts:
        - name: token-vol
          mountPath: "/service-account"
          readOnly: true
  serviceAccountName: default
  volumes:
    - name: token-vol
      projected:
        sources:
          - serviceAccountToken:
            audience: api
            expirationSeconds: 3600
            path: token
