---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secontextpodcat1uid0
    app: test
    test-network-function.com/generic: target
    test-network-function.com/container: target
  name: secontextpodcat1uid0
  namespace: tnf
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000900000
    runAsGroup: 1000900000
    fsGroup: 1000900000
  containers:
    - image: quay.io/testnetworkfunction/cnf-test-partner:latest
      name: test
      resources: {}
      securityContext:
        seLinuxOptions:
          level: "s0:c30,c15"
        capabilities:
          drop: ["KILL", "MKNOD", "SETUID", "SETGID"]
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        privileged: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
