---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secontextpodcat2
    app: test
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
  name: secontextpodcat2
  namespace: tnf
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000900000
    runAsGroup: 1000900000
    fsGroup: 1000900000
  containers:
    - image: quay.io/testnetworkfunction/cnf-test-partner:latest
      name: test
      resources: {}
      securityContext:
        seLinuxOptions:
          level: "s0:c30,c15"
        capabilities:
          drop: ["KILL", "MKNOD", "SETUID", "SETGID"]
          add: ["NET_ADMIN", "NET_RAW"]
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        privileged: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
