---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: tnf
automountServiceAccountToken: true
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: serviceaccountpod
    app: test
    test-network-function.com/generic: target
    test-network-function.com/container: target
  name: serviceaccountpod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  serviceAccountName: app-service-account
  containers:
    - image: nginx
      name: serviceaccountpod
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
