---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: serviceaccounttokenpod
    app: test
    redhat-best-practices-for-k8s.com/generic: target
    redhat-best-practices-for-k8s.com/container: target
  name: serviceaccounttokenpod
  namespace: tnf
spec:
  # automountServiceAccountToken should be set to false explicitly to satisfy testing requirements.
  # Please visit this link to learn more:
  # https://github.com/redhat-best-practices-for-k8s/certsuite/blob/main/CATALOG.md#pod-automount-service-account-token
  automountServiceAccountToken: true
  containers:
    - image: nginx
      name: serviceaccounttokenpod
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
