---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sysadminpod
    app: test
    test-network-function.com/generic: target
    test-network-function.com/container: target
  name: sysadminpod
  namespace: tnf
spec:
  automountServiceAccountToken: false
  containers:
    - image: nginx
      name: sysadminpod
      resources: {}
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]  # SYS_ADMIN should not be set.
  dnsPolicy: ClusterFirst
  restartPolicy: Always
