kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  LocalStorageCapacityIsolation: false
networking:
  ipFamily: dual
  disableDefaultCNI: true
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
