apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ NET_NAME_NUM }}
  namespace: {{ TNF_EXAMPLE_CNF_NAMESPACE }}
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "range": "{{ IP_NUM }}"
      }
    }'
