name: start-k8s-cluster
description: Creates and configures a k8s cluster for all things TNF-related
inputs:
  working_directory:
    default: .
  oc_kcm_timeout:
    default: 5m

runs:
  using: 'composite'
  steps:
    - name: Run Bootstrap Cluster
      run: make bootstrap-cluster
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Run Bootstrap Docker
      run: make bootstrap-docker-ubuntu-local
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Run Bootstrap Python
      run: make bootstrap-python-ubuntu-local
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Start the cluster
      run: make rebuild-cluster
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    # Wait for all pods to be ready
    - name: Wait for all pods ready
      run: |
        echo "Waiting for kube-controller-manager... (timeout: ${{ inputs.oc_kcm_timeout }})" && \
        oc wait -n kube-system --for=condition=ready pod --all=true --timeout=${{ inputs.oc_kcm_timeout }}
      shell: bash

    - name: Display kube-system pods
      run: oc get pods -n kube-system -o wide
      shell: bash
      
    - name: Display cluster nodes
      run: oc get nodes
      shell: bash

    - name: Display a friendly summary message
      run: echo "TNF-compatible cluster is ready to go! Have fun!"
      shell: bash
