name: Test the partner pod installation
on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  test-test-partner:
    name: 'Test the partner pod on minikube'
    runs-on: ubuntu-20.04
    env:
      DEFAULT_NAMESPACE: default
      TPP_CONTAINER_NAME: partner
      DEFAULT_TIMEOUT: 180s

    steps:
      - uses: actions/checkout@v2

      - name: Start the minikube cluster
        uses: ./.github/actions/start-minikube

      - name: Create the partner pod using the instructions in the README
        run: |
          make install-partner-pods

      - name: Wait for the partner pod to be ready
        run: oc wait pod --for=condition=ready -l 'app=tnfpartner' -n $DEFAULT_NAMESPACE --timeout=$DEFAULT_TIMEOUT

      - name: Ensure only one partner pod with the label is present
        run: '[[ $(oc get pods -n $DEFAULT_NAMESPACE -l "app=tnfpartner" -o name | wc -l) -eq "1" ]]'

      - name: Discover the name of the partner pod
        run: |
          echo "TPP_POD_NAME=$(oc get pods -n $DEFAULT_NAMESPACE -l 'app=tnfpartner' -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV

      - name: '(partner pod) Test: Check if ping is installed'
        run: oc exec -n $DEFAULT_NAMESPACE -i $TPP_POD_NAME -c $TPP_CONTAINER_NAME -- which ping

      - name: '(partner pod) Test: Check if ip is installed'
        run: oc exec -n $DEFAULT_NAMESPACE -i $TPP_POD_NAME -c $TPP_CONTAINER_NAME -- which ip

      - name: '(partner pod) Test: Check if ssh is installed'
        run: oc exec -n $DEFAULT_NAMESPACE -i $TPP_POD_NAME -c $TPP_CONTAINER_NAME -- which ssh
