name: Test the partner pod installation
on: [push, pull_request]
defaults:
  run:
    shell: bash
    working-directory: test-partner

jobs:
  test-local-test-infra:
    name: 'Test the partner pod on minikube'
    runs-on: ubuntu-20.04
    env:
      TNF_NAMESPACE: tnf
      TPP_CONTAINER_NAME: partner
      DEFAULT_TIMEOUT: 90s

    steps:
      - uses: actions/checkout@v2

      - name: Start the minikube cluster
        uses: ./.github/actions/start-minikube

      - name: Add a proper label to the minikube node
        run: oc label nodes minikube role=partner

      - name: Create the partner pod using the instructions in the README
        run: |
          oc create -f ./namespace.yaml
          oc create -f ./partner.yaml

      - name: Wait for the partner pod to be ready
        run: oc wait pod -n $TNF_NAMESPACE --for=condition=ready -l 'app=partner' --timeout=$DEFAULT_TIMEOUT

      - name: Ensure only one partner pod with the label is present
        run: '[[ $(oc get pods -n $TNF_NAMESPACE -l "app=partner" -o name | wc -l) -eq "1" ]]'

      - name: Discover the name of the partner pod
        run: |
          echo "TPP_POD_NAME=$(oc get pods -n $TNF_NAMESPACE -l 'app=partner' -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV

      - name: '(partner pod) Test: Check if ping is installed'
        run: oc exec -n $TNF_NAMESPACE -i $TPP_POD_NAME -c $TPP_CONTAINER_NAME -- which ping

      - name: '(partner pod) Test: Check if ip is installed'
        run: oc exec -n $TNF_NAMESPACE -i $TPP_POD_NAME -c $TPP_CONTAINER_NAME -- which ip

      - name: '(partner pod) Test: Check if ssh is installed'
        run: oc exec -n $TNF_NAMESPACE -i $TPP_POD_NAME -c $TPP_CONTAINER_NAME -- which ssh
