name: 'Test multi-arch image builds on PRs'

on:
  pull_request:
    branches: [main]
    paths:
      - 'test-partner/Dockerfile*'
      - 'testapp/**'
      - '.github/workflows/pr-image-build.yaml'
  workflow_dispatch:

permissions: read-all

defaults:
  run:
    shell: bash

env:
  REGISTRY: quay.io
  SAMPLE_WORKLOAD_IMAGE_NAME: redhat-best-practices-for-k8s/certsuite-sample-workload
  DEBUG_PARTNER_IMAGE_NAME: testnetworkfunction/debug-partner
  IMAGE_TAG: pr-test

jobs:
  build-sample-workload-image:
    name: 'Build multi-arch `certsuite-sample-workload` image'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Setup Docker Storage
        uses: ./.github/actions/setup-docker-storage

      - name: 'Build multi-arch `certsuite-sample-workload` image (no push)'
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          push: false
          file: ./test-partner/Dockerfile
          tags: '${{ env.SAMPLE_WORKLOAD_IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=certsuite-sample-workload-pr
          cache-to: type=gha,mode=max,scope=certsuite-sample-workload-pr

  build-debug-partner-image:
    name: 'Build multi-arch `debug-partner` image'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Setup Docker Storage
        uses: ./.github/actions/setup-docker-storage

      - name: 'Build multi-arch `debug-partner` image (no push)'
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          push: false
          file: ./test-partner/Dockerfile.debug-partner
          tags: '${{ env.DEBUG_PARTNER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=debug-partner-pr
          cache-to: type=gha,mode=max,scope=debug-partner-pr
